<?php

declare(strict_types=1);

return [
    // Навигация
    'MENU_HOME'             => 'Home',
    'BREADCRUMB_HOME'       => 'Encryption Online',
    'BREADCRUMB_HOME_FULL'  => 'Online Encryption and Encoding Systems',
    'MENU_CONTACTS'         => 'Contacts',
    'MENU_SITEMAP'          => 'Sitemap',
    'MENU_CABINET'          => 'My Account',
    'MENU_ADMIN'            => 'Admin',
    'MENU_TOOLS'            => 'Tools',
    'MENU_CLASSICAL_CIPHERS' => 'Classical ciphers',
    'MENU_ENCODING'         => 'Data encoding',

    // Авторизация
    'AUTH_SIGN_IN'          => 'Sign In',
    'AUTH_SIGN_OUT'         => 'Sign Out',
    'AUTH_CABINET'          => 'My Account',
    'AUTH_EMAIL'            => 'Email',
    'AUTH_NAME'             => 'Name',
    'AUTH_PASSWORD'         => 'Password',
    'AUTH_PASSWORD_CONFIRMATION' => 'Confirm password',
    'AUTH_SIGN_IN_TITLE'    => 'Sign In',
    'AUTH_SIGN_UP'          => 'Sign Up',
    'AUTH_SIGN_UP_TITLE'    => 'Registration',
    'AUTH_ALREADY_HAVE_ACCOUNT' => 'Already have an account? Sign in',
    'AUTH_REGISTERING'      => 'Creating your account...',
    'AUTH_REGISTRATION_SUCCESS' => 'Registration completed successfully.',
    'AUTH_REGISTRATION_FAILED' => 'Failed to create account. Please try again.',
    'AUTH_POLICY_AGREEMENT_TEXT' => 'I agree to the',
    'AUTH_POLICY_AGREEMENT_LINK' => 'privacy policy',
    'AUTH_ERROR_NAME_REQUIRED' => 'Name is required.',
    'AUTH_ERROR_NAME_LENGTH' => 'Name must be between 2 and 100 characters.',
    'AUTH_ERROR_EMAIL_REQUIRED' => 'Email is required.',
    'AUTH_ERROR_EMAIL_INVALID' => 'Please enter a valid email.',
    'AUTH_ERROR_PASSWORD_REQUIRED' => 'Password is required.',
    'AUTH_ERROR_PASSWORD_LENGTH' => 'Password must be at least 8 characters.',
    'AUTH_ERROR_CONFIRMATION_REQUIRED' => 'Password confirmation is required.',
    'AUTH_ERROR_CONFIRMATION_MISMATCH' => 'Passwords do not match.',
    'AUTH_ERROR_POLICY_REQUIRED' => 'You must agree to the privacy policy.',
    'AUTH_INVALID'          => 'Invalid email or password.',

    // Главная
    'HOME_TITLE'                       => 'CiphersOnline — cipher, encoding and cryptography tools',
    'HOME_META_DESCRIPTION'            => 'Online tools for ciphers, encoding and data conversion: Base64, JWT, Caesar, Hex, URL Encode and more — for developers, learning and analysis.',
    'HOME_HERO_TITLE'                  => 'Online tools for encryption, encoding and data conversion',
    'HOME_HERO_SUBTITLE'               => 'Classical ciphers, Base64, JWT, Hex, URL Encode and other tools for developers, learning and data analysis.',
    'HOME_SEARCH_PLACEHOLDER'          => 'Search tools — Base64, Caesar, JWT…',
    'HOME_QUICK_ACCESS'                => 'Quick access',
    'HOME_CATEGORIES_TITLE'            => 'Main categories',
    'HOME_CATEGORIES_LEAD'             => 'Navigation hubs grouped by purpose. Each category bundles related tools, explanatory blocks and use cases.',
    'HOME_TOOLS_COUNT'                 => ':count tool|:count tools',
    'HOME_OPEN_CATEGORY'               => 'Open category',
    'HOME_COMING_SOON'                 => 'Coming soon',
    'HOME_CATEGORY_HASHING_NAME'       => 'Hashing and Cryptography',
    'HOME_CATEGORY_HASHING_DESC'       => 'MD5, SHA256, HMAC, checksums and cryptographic hash functions.',
    'HOME_CATEGORY_CRYPTANALYSIS_NAME' => 'Cryptanalysis and Text Analysis',
    'HOME_CATEGORY_CRYPTANALYSIS_DESC' => 'Frequency analysis, entropy, index of coincidence and other tools for analyzing ciphers.',
    'HOME_POPULAR_TOOLS_TITLE'         => 'Popular tools',
    'HOME_POPULAR_TOOLS_LEAD'          => 'Most-used tools from the catalog — start here.',
    'HOME_USE_CASES_TITLE'             => 'Popular use cases',
    'HOME_USE_CASES_LEAD'              => 'Common tasks and the tools that solve them.',
    'HOME_USE_CASE_JWT_TITLE'          => 'Decode JWT tokens',
    'HOME_USE_CASE_JWT_DESC'           => 'Inspect the header, payload and signature of a JSON Web Token.',
    'HOME_USE_CASE_BASE64_TITLE'       => 'Encode API payloads to Base64',
    'HOME_USE_CASE_BASE64_DESC'        => 'Convert text and binary data to Base64 for safe transport.',
    'HOME_USE_CASE_CAESAR_TITLE'       => 'Analyze classical ciphers',
    'HOME_USE_CASE_CAESAR_DESC'        => 'Encrypt and decrypt text with the classical Caesar cipher.',
    'HOME_USE_CASE_BINARY_TITLE'       => 'Convert text to binary',
    'HOME_USE_CASE_BINARY_DESC'        => 'Convert characters to a binary representation byte-by-byte.',
    'HOME_USE_CASE_URL_TITLE'          => 'Decode URL parameters',
    'HOME_USE_CASE_URL_DESC'           => 'Encode and decode special characters in URL query strings.',
    'HOME_USE_CASE_HEX_TITLE'          => 'Convert text to Hex',
    'HOME_USE_CASE_HEX_DESC'           => 'Inspect and convert text or binary data to hexadecimal form.',
    'HOME_EDU_TITLE'                   => 'Encoding and encryption — in short',
    'HOME_EDU_LEAD'                    => 'A quick orientation in three compact blocks.',
    'HOME_EDU_CARD_1_TITLE'            => 'Encoding vs encryption',
    'HOME_EDU_CARD_1_TEXT'             => 'Encoding transforms data into a different representation without a key. Encryption protects data with a key and is reversible only by who holds it.',
    'HOME_EDU_CARD_2_TITLE'            => 'What classical ciphers are',
    'HOME_EDU_CARD_2_TEXT'             => 'Substitution and transposition schemes from before the digital era — Caesar, Vigenère, Playfair and more. Useful for learning and CTF challenges.',
    'HOME_EDU_CARD_3_TITLE'            => 'Where Base64 and Hex are used',
    'HOME_EDU_CARD_3_TEXT'             => 'Binary data inside text protocols (HTTP, JSON, email), inspecting bytes while debugging and stable representation of arbitrary content.',
    'HOME_GROWING_TITLE'               => 'Catalog is growing',
    'HOME_GROWING_LEAD'                => 'Recently added tools in the catalog.',
    'HOME_BADGE_NEW'                   => 'New',

    // Контакты
    'CONTACTS_TITLE'        => 'Contacts',
    'CONTACTS_EMAIL'        => 'Email',
    'CONTACTS_PHONE'        => 'Phone',
    'CONTACTS_ADDRESS'      => 'Address',
    'CONTACT_DESCRIPTION'   => 'Leave a message and we will get back to you shortly.',
    'CONTACT_FEATURE_FAST'  => 'Fast response',
    'CONTACT_FEATURE_SECURE' => 'Secure processing',
    'CONTACT_FEATURE_FRIENDLY' => 'Friendly support',
    'CONTACT_YOUR_NAME'     => 'Your name',
    'CONTACT_YOUR_EMAIL'    => 'Your email',
    'CONTACT_MESSAGE'       => 'Message',
    'CONTACT_SEND'          => 'Send',
    'CONTACT_SENDING'       => 'Sending...',
    'CONTACT_SUCCESS'       => 'Message sent. Thank you!',
    'CONTACT_FAILED'        => 'Failed to send message. Please try again.',
    'CONTACT_ERROR_NAME'    => 'Enter your name (up to 100 characters).',
    'CONTACT_ERROR_EMAIL'   => 'Enter a valid email (up to 100 characters).',
    'CONTACT_ERROR_MESSAGE' => 'Enter your message.',
    'CONTACT_ERROR_MESSAGE_MAX' => 'Message is too long (maximum 10000 characters).',

    // Кабинет
    'CABINET_TITLE'         => 'My Account',
    'CABINET_STATUS'        => 'Active',
    'CABINET_ROLE'          => 'User',
    'CABINET_ID'            => 'ID',
    'CABINET_STATUS_LBL'    => 'Status',
    'CABINET_ACTIVITY'      => 'Activity',
    'CABINET_ACTIVITY_TXT'  => 'User activity history will be shown here.',
    'CABINET_SIGN_OUT'      => 'Sign out of account',

    // Карта сайта
    'SITEMAP_TITLE'         => 'Sitemap',
    'SITEMAP_MAIN_PAGES'    => 'Main pages',
    'SITEMAP_PAGES'         => 'Pages',

    // Множественное число — pipe-разделённые формы (one|other)
    'ITEMS_COUNT'   => ':count item|:count items',
    'USERS_ONLINE'  => ':count user online|:count users online',
    'DAYS_AGO'      => ':count day ago|:count days ago',
    // ICU plural
    'MESSAGES_ICU'  => 'You have {count, plural, =0 {no messages} one {# message} other {# messages}}.',
    'WELCOME_ICU'   => 'Hello, {name}! You have {count, plural, one {# new item} other {# new items}}.',

    // 404
    'ERROR_404_TITLE'               => '404 - Page Not Found',
    'ERROR_404_HEADING'             => 'Page Not Found',
    'ERROR_404_TEXT'                => 'The link may be outdated or the page has been moved. Try searching the site or use one of the popular sections below.',
    'ERROR_404_SEARCH_LABEL'        => 'Search the site',
    'ERROR_404_SEARCH_PLACEHOLDER'  => 'For example: contacts, account, privacy policy',
    'ERROR_404_SEARCH_BUTTON'       => 'Search',
    'ERROR_404_HOME_TITLE'          => 'Home',
    'ERROR_404_HOME_TEXT'           => 'Return to the homepage.',
    'ERROR_404_CONTACTS_TITLE'      => 'Contacts',
    'ERROR_404_CONTACTS_TEXT'       => 'How to reach us.',
    'ERROR_404_LOGIN_TITLE'         => 'Sign In',
    'ERROR_404_LOGIN_TEXT'          => 'Authorize in your account.',
    'ERROR_404_CABINET_TITLE'       => 'My Account',
    'ERROR_404_CABINET_TEXT'        => 'Go to the user section.',

    // Инструменты шифрования/кодирования (workspace)
    'CIPHER_TOOL_TAB_ENCODE' => 'Encode',
    'CIPHER_TOOL_TAB_DECODE' => 'Decode',
    'CIPHER_TOOL_INPUT_LABEL_ENCODE' => 'Input',
    'CIPHER_TOOL_INPUT_LABEL_DECODE' => 'Encoded input',
    'CIPHER_TOOL_PLACEHOLDER_ENCODE' => 'Enter text...',
    'CIPHER_TOOL_PLACEHOLDER_DECODE' => 'Paste encoded value...',
    'CIPHER_TOOL_PLACEHOLDER_OUTPUT' => 'Result will appear here',
    'CIPHER_TOOL_RESULT_LABEL' => 'Result',
    'CIPHER_TOOL_TRY_LABEL' => 'Try:',
    'CIPHER_TOOL_COPY_LABEL' => 'Copy',
    'CIPHER_TOOL_SHARE_LABEL' => 'Share',
    'CIPHER_TOOL_CLEAR_LABEL' => 'Clear',
    'CIPHER_TOOL_CHARS_LABEL' => 'chars',
    'CIPHER_TOOL_BYTES_LABEL' => 'bytes',
    'CIPHER_TOOL_EXAMPLES_TITLE' => 'Examples',
    'CIPHER_TOOL_FAQ_TITLE' => 'FAQ',
    'CIPHER_TOOL_RELATED_TITLE' => 'Related tools',
    'CIPHER_TOOL_INFO_TITLE' => 'Info',
    'CIPHER_CATEGORY_TOOLS_TITLE_CIPHER' => 'Cipher Tools',
    'CIPHER_CATEGORY_TOOLS_TITLE_ENCODING' => 'Encoding Tools',
    'CIPHER_CATEGORY_POPULAR_TASKS_TITLE' => 'Popular Tasks',
    'CIPHER_CATEGORY_USED_TOGETHER_TITLE' => 'Often Used Together',
    'CIPHER_TOOL_INPUT_TAG' => 'Input',
    'CIPHER_TOOL_OUTPUT_TAG' => 'Output',
    'CIPHER_TOOL_USE_EXAMPLE' => 'Use example',
    'CIPHER_TOOL_ALL_IN_CATEGORY' => 'All :category',
    'CIPHER_TOOL_FEEDBACK_INVALID' => 'Invalid input for current mode.',
    'CIPHER_TOOL_FEEDBACK_RESULT_COPIED' => 'Result copied.',
    'CIPHER_TOOL_FEEDBACK_RESULT_COPY_FAILED' => 'Unable to copy result.',
    'CIPHER_TOOL_FEEDBACK_URL_COPIED' => 'Page URL copied.',
    'CIPHER_TOOL_FEEDBACK_URL_COPY_FAILED' => 'Unable to copy page URL.',
    'CIPHER_TOOL_TRUST_LOCAL' => 'Client-side processing only',
    'CIPHER_TOOL_TRUST_UTF8' => 'UTF-8 and Unicode support',
    'CIPHER_TOOL_TRUST_API' => 'API and payload friendly',
    'CIPHER_TOOL_TRUST_PRIVATE' => 'Input is not sent to server',
];
