<?php

declare(strict_types=1);

return [
    // Навигация
    'MENU_NAV'              => 'Меню',
    'MENU_HOME'             => 'Главная',
    'MENU_FAVORITES'        => 'Избранное',
    'BREADCRUMB_HOME'       => 'Шифрование онлайн',
    'BREADCRUMB_HOME_FULL'  => 'Системы шифрования и кодирования онлайн',
    'MENU_CONTACTS'         => 'Контакты',
    'MENU_SITEMAP'          => 'Карта сайта',
    'MENU_CABINET'          => 'Кабинет',
    'MENU_ADMIN'            => 'Админ',
    'MENU_TOOLS'            => 'Инструменты',
    'MENU_CLASSICAL_CIPHERS' => 'Классические шифры',
    'MENU_ENCODING'         => 'Кодирование данных',

    // Авторизация
    'AUTH_SIGN_IN'          => 'Войти',
    'AUTH_SIGN_OUT'         => 'Выйти',
    'AUTH_CABINET'          => 'Кабинет',
    'AUTH_EMAIL'            => 'Email',
    'AUTH_NAME'             => 'Имя',
    'AUTH_PASSWORD'         => 'Пароль',
    'AUTH_PASSWORD_CONFIRMATION' => 'Подтверждение пароля',
    'AUTH_SIGN_IN_TITLE'    => 'Вход в систему',
    'AUTH_SIGN_UP'          => 'Регистрация',
    'AUTH_SIGN_UP_TITLE'    => 'Регистрация',
    'AUTH_ALREADY_HAVE_ACCOUNT' => 'Уже есть аккаунт? Войти',
    'AUTH_REGISTERING'      => 'Создаём аккаунт...',
    'AUTH_REGISTRATION_SUCCESS' => 'Регистрация успешно завершена.',
    'AUTH_REGISTRATION_FAILED' => 'Не удалось создать аккаунт. Попробуйте ещё раз.',
    'AUTH_POLICY_AGREEMENT_TEXT' => 'Я согласен с',
    'AUTH_POLICY_AGREEMENT_LINK' => 'политикой конфиденциальности',
    'AUTH_ERROR_NAME_REQUIRED' => 'Введите имя.',
    'AUTH_ERROR_NAME_LENGTH' => 'Имя должно быть от 2 до 100 символов.',
    'AUTH_ERROR_EMAIL_REQUIRED' => 'Введите email.',
    'AUTH_ERROR_EMAIL_INVALID' => 'Введите корректный email.',
    'AUTH_ERROR_PASSWORD_REQUIRED' => 'Введите пароль.',
    'AUTH_ERROR_PASSWORD_LENGTH' => 'Пароль должен быть не короче 8 символов.',
    'AUTH_ERROR_CONFIRMATION_REQUIRED' => 'Подтвердите пароль.',
    'AUTH_ERROR_CONFIRMATION_MISMATCH' => 'Пароли не совпадают.',
    'AUTH_ERROR_POLICY_REQUIRED' => 'Нужно согласиться с политикой конфиденциальности.',
    'AUTH_INVALID'          => 'Неверный email или пароль.',

    // Главная
    'HOME_TITLE'                       => 'CiphersOnline — инструменты для шифрования, кодирования и криптографии',
    'HOME_META_DESCRIPTION'            => 'Онлайн-инструменты для шифров, кодирования и преобразования данных: Base64, JWT, Caesar, Hex, URL Encode и другие — для разработчиков, обучения и анализа.',
    'HOME_HERO_TITLE'                  => 'Онлайн-инструменты для шифрования, кодирования и преобразования данных',
    'HOME_HERO_SUBTITLE'               => 'Классические шифры, Base64, JWT, Hex, URL Encode и другие инструменты для разработчиков, обучения и анализа данных.',
    'HOME_SEARCH_PLACEHOLDER'          => 'Поиск инструментов — Base64, Caesar, JWT…',
    'HOME_SEARCH_NO_RESULTS'           => 'Инструменты не найдены',
    'HOME_QUICK_ACCESS'                => 'Быстрый доступ',
    'HOME_CATEGORIES_TITLE'            => 'Основные категории',
    'HOME_CATEGORIES_LEAD'             => 'Навигационные хабы по назначению. Каждая категория объединяет связанные инструменты, пояснения и сценарии использования.',
    'HOME_TOOLS_COUNT'                 => ':count инструмент|:count инструмента|:count инструментов',
    'HOME_OPEN_CATEGORY'               => 'Открыть категорию',
    'HOME_COMING_SOON'                 => 'Скоро',
    'HOME_CATEGORY_HASHING_NAME'       => 'Хеширование и криптография',
    'HOME_CATEGORY_HASHING_DESC'       => 'MD5, SHA256, HMAC, checksum и криптографические хеш-функции.',
    'HOME_CATEGORY_CRYPTANALYSIS_NAME' => 'Криптоанализ и анализ текста',
    'HOME_CATEGORY_CRYPTANALYSIS_DESC' => 'Частотный анализ, энтропия, индекс совпадений и другие инструменты анализа шифров.',
    'HOME_POPULAR_TOOLS_TITLE'         => 'Популярные инструменты',
    'HOME_POPULAR_TOOLS_LEAD'          => 'Самые востребованные инструменты каталога — начните отсюда.',
    'HOME_USE_CASES_TITLE'             => 'Популярные задачи',
    'HOME_USE_CASES_LEAD'              => 'Типичные задачи и инструменты, которые их решают.',
    'HOME_USE_CASE_JWT_TITLE'          => 'Декодировать JWT-токены',
    'HOME_USE_CASE_JWT_DESC'           => 'Посмотреть заголовок, payload и подпись JSON Web Token.',
    'HOME_USE_CASE_BASE64_TITLE'       => 'Закодировать payload API в Base64',
    'HOME_USE_CASE_BASE64_DESC'        => 'Преобразовать текст и бинарные данные в Base64 для безопасной передачи.',
    'HOME_USE_CASE_CAESAR_TITLE'       => 'Изучить классические шифры',
    'HOME_USE_CASE_CAESAR_DESC'        => 'Зашифровать и расшифровать текст классическим шифром Цезаря.',
    'HOME_USE_CASE_BINARY_TITLE'       => 'Перевести текст в двоичный код',
    'HOME_USE_CASE_BINARY_DESC'        => 'Преобразовать символы в побайтовое двоичное представление.',
    'HOME_USE_CASE_URL_TITLE'          => 'Декодировать URL-параметры',
    'HOME_USE_CASE_URL_DESC'           => 'Закодировать и раскодировать спецсимволы в URL-строках.',
    'HOME_USE_CASE_HEX_TITLE'          => 'Перевести текст в Hex',
    'HOME_USE_CASE_HEX_DESC'           => 'Изучить и перевести текст или бинарные данные в шестнадцатеричный вид.',
    'HOME_EDU_TITLE'                   => 'Кодирование и шифрование — коротко',
    'HOME_EDU_LEAD'                    => 'Быстрое введение в трёх компактных блоках.',
    'HOME_EDU_CARD_1_TITLE'            => 'Кодирование vs шифрование',
    'HOME_EDU_CARD_1_TEXT'             => 'Кодирование меняет представление данных без секретного ключа. Шифрование защищает данные ключом и обратимо только для того, у кого ключ есть.',
    'HOME_EDU_CARD_2_TITLE'            => 'Что такое классические шифры',
    'HOME_EDU_CARD_2_TEXT'             => 'Схемы замены и перестановки эпохи до цифровых вычислений — Caesar, Vigenère, Playfair и другие. Полезны для обучения и CTF-задач.',
    'HOME_EDU_CARD_3_TITLE'            => 'Где применяются Base64 и Hex',
    'HOME_EDU_CARD_3_TEXT'             => 'Бинарные данные в текстовых протоколах (HTTP, JSON, email), просмотр байтов при отладке и стабильное представление произвольного контента.',
    'HOME_GROWING_TITLE'               => 'Каталог расширяется',
    'HOME_GROWING_LEAD'                => 'Недавно добавленные инструменты каталога.',
    'HOME_BADGE_NEW'                   => 'Новое',

    // Контакты
    'CONTACTS_TITLE'        => 'Контакты',
    'CONTACTS_EMAIL'        => 'Email',
    'CONTACTS_PHONE'        => 'Телефон',
    'CONTACTS_ADDRESS'      => 'Адрес',
    'CONTACT_DESCRIPTION'   => 'Оставьте сообщение, и мы свяжемся с вами в ближайшее время.',
    'CONTACT_FEATURE_FAST'  => 'Быстрый ответ',
    'CONTACT_FEATURE_SECURE' => 'Безопасная обработка',
    'CONTACT_FEATURE_FRIENDLY' => 'Дружелюбная поддержка',
    'CONTACT_YOUR_NAME'     => 'Ваше имя',
    'CONTACT_YOUR_EMAIL'    => 'Ваш email',
    'CONTACT_MESSAGE'       => 'Сообщение',
    'CONTACT_SEND'          => 'Отправить',
    'CONTACT_SENDING'       => 'Отправляем...',
    'CONTACT_SUCCESS'       => 'Сообщение отправлено. Спасибо!',
    'CONTACT_FAILED'        => 'Не удалось отправить сообщение. Попробуйте ещё раз.',
    'CONTACT_ERROR_NAME'    => 'Введите имя (до 100 символов).',
    'CONTACT_ERROR_EMAIL'   => 'Введите корректный email (до 100 символов).',
    'CONTACT_ERROR_MESSAGE' => 'Введите текст сообщения.',
    'CONTACT_ERROR_MESSAGE_MAX' => 'Сообщение слишком длинное (максимум 10000 символов).',

    // Кабинет
    'CABINET_TITLE'         => 'Личный кабинет',
    'CABINET_STATUS'        => 'Активен',
    'CABINET_ROLE'          => 'Пользователь',
    'CABINET_ID'            => 'ID',
    'CABINET_STATUS_LBL'    => 'Статус',
    'CABINET_ACTIVITY'      => 'Активность',
    'CABINET_ACTIVITY_TXT'  => 'Здесь будет история активности пользователя.',
    'CABINET_SIGN_OUT'      => 'Выйти из аккаунта',

    // Избранное
    'FAVORITES_PAGE_TITLE'   => 'Избранное — CiphersOnline',
    'FAVORITES_PAGE_META'    => 'Сохранённые инструменты шифрования и кодирования.',
    'FAVORITES_PAGE_HEADING' => 'Избранное',
    'FAVORITES_PAGE_DESC'    => 'Инструменты, которые вы сохранили для быстрого доступа.',
    'FAVORITES_EMPTY_TEXT'   => 'Здесь пока ничего нет. Нажмите ★ на странице любого инструмента, чтобы добавить его сюда.',
    'FAVORITES_BROWSE_BTN'   => 'Перейти к инструментам',

    // Карта сайта
    'SITEMAP_TITLE'         => 'Карта сайта',
    'SITEMAP_META'          => 'Каталог всех инструментов шифрования и кодирования на CiphersOnline.',
    'SITEMAP_DESC'          => 'Все доступные инструменты шифрования и кодирования, сгруппированные по категориям.',
    'SITEMAP_MAIN_PAGES'    => 'Основные страницы',
    'SITEMAP_PAGES'         => 'Страницы',

    // Множественное число — pipe-разделённые формы (one|few|many)
    'ITEMS_COUNT'   => ':count элемент|:count элемента|:count элементов',
    'USERS_ONLINE'  => ':count пользователь онлайн|:count пользователя онлайн|:count пользователей онлайн',
    'DAYS_AGO'      => ':count день назад|:count дня назад|:count дней назад',
    // ICU plural
    'MESSAGES_ICU'  => 'У вас {count, plural, =0 {нет сообщений} one {# сообщение} few {# сообщения} many {# сообщений} other {# сообщения}}.',
    'WELCOME_ICU'   => 'Привет, {name}! У вас {count, plural, one {# новый элемент} few {# новых элемента} many {# новых элементов} other {# новых элемента}}.',

    // 404
    'ERROR_404_TITLE'               => '404 - Страница не найдена',
    'ERROR_404_HEADING'             => 'Страница не найдена',
    'ERROR_404_TEXT'                => 'Возможно, ссылка устарела или страница была перемещена. Попробуйте поиск или перейдите в популярные разделы ниже.',
    'ERROR_404_SEARCH_LABEL'        => 'Поиск по сайту',
    'ERROR_404_SEARCH_PLACEHOLDER'  => 'Например: контакты, кабинет, политика конфиденциальности',
    'ERROR_404_SEARCH_BUTTON'       => 'Найти',
    'ERROR_404_HOME_TITLE'          => 'Главная',
    'ERROR_404_HOME_TEXT'           => 'Вернуться на стартовую страницу.',
    'ERROR_404_CONTACTS_TITLE'      => 'Контакты',
    'ERROR_404_CONTACTS_TEXT'       => 'Как с нами связаться.',
    'ERROR_404_LOGIN_TITLE'         => 'Вход',
    'ERROR_404_LOGIN_TEXT'          => 'Авторизация в личный кабинет.',
    'ERROR_404_CABINET_TITLE'       => 'Кабинет',
    'ERROR_404_CABINET_TEXT'        => 'Перейти в пользовательский раздел.',

    // Инструменты шифрования/кодирования (workspace)
    'CIPHER_TOOL_TAB_ENCODE' => 'Кодировать',
    'CIPHER_TOOL_TAB_DECODE' => 'Декодировать',
    'CIPHER_TOOL_INPUT_LABEL_ENCODE' => 'Входные данные',
    'CIPHER_TOOL_INPUT_LABEL_DECODE' => 'Закодированные данные',
    'CIPHER_TOOL_PLACEHOLDER_ENCODE' => 'Введите текст...',
    'CIPHER_TOOL_PLACEHOLDER_DECODE' => 'Вставьте закодированное значение...',
    'CIPHER_TOOL_PLACEHOLDER_OUTPUT' => 'Результат появится здесь',
    'CIPHER_TOOL_RESULT_LABEL' => 'Результат',
    'CIPHER_TOOL_TRY_LABEL' => 'Попробовать:',
    'CIPHER_TOOL_COPY_LABEL' => 'Копировать',
    'CIPHER_TOOL_SHARE_LABEL' => 'Поделиться',
    'CIPHER_TOOL_CLEAR_LABEL' => 'Очистить',
    'CIPHER_TOOL_CHARS_LABEL' => 'симв.',
    'CIPHER_TOOL_BYTES_LABEL' => 'байт',
    'CIPHER_TOOL_EXAMPLES_TITLE' => 'Примеры',
    'CIPHER_TOOL_FAQ_TITLE' => 'FAQ',
    'CIPHER_TOOL_RELATED_TITLE' => 'Связанные инструменты',
    'CIPHER_TOOL_INFO_TITLE' => 'Информация',
    'CIPHER_CATEGORY_TOOLS_TITLE_CIPHER' => 'Инструменты шифрования',
    'CIPHER_CATEGORY_TOOLS_TITLE_ENCODING' => 'Инструменты кодирования',
    'CIPHER_CATEGORY_POPULAR_TASKS_TITLE' => 'Популярные задачи',
    'CIPHER_CATEGORY_USED_TOGETHER_TITLE' => 'Часто используют вместе',
    'CIPHER_TOOL_INPUT_TAG' => 'Вход',
    'CIPHER_TOOL_OUTPUT_TAG' => 'Выход',
    'CIPHER_TOOL_USE_EXAMPLE' => 'Использовать пример',
    'CIPHER_TOOL_EXAMPLE_KEY_LABEL' => 'Ключ',
    'CIPHER_TOOL_ALL_IN_CATEGORY' => 'Все инструменты: :category',
    'CIPHER_TOOL_FEEDBACK_INVALID' => 'Некорректные данные для выбранного режима.',
    'CIPHER_TOOL_FEEDBACK_RESULT_COPIED' => 'Результат скопирован.',
    'CIPHER_TOOL_FEEDBACK_RESULT_COPY_FAILED' => 'Не удалось скопировать результат.',
    'CIPHER_TOOL_FEEDBACK_URL_COPIED' => 'Ссылка на страницу скопирована.',
    'CIPHER_TOOL_FEEDBACK_URL_COPY_FAILED' => 'Не удалось скопировать ссылку на страницу.',
    'CIPHER_TOOL_FAVORITE_ADD'              => 'Добавить в избранное',
    'CIPHER_TOOL_FAVORITE_REMOVE'           => 'Убрать из избранного',
    'CIPHER_TOOL_FEEDBACK_FAVORITE_ADDED'   => '★ Добавлено в избранное',
    'CIPHER_TOOL_FEEDBACK_FAVORITE_REMOVED' => '☆ Убрано из избранного',
    'CIPHER_TOOL_TRUST_LOCAL' => 'Обработка выполняется локально в браузере',
    'CIPHER_TOOL_TRUST_UTF8' => 'Поддержка UTF-8 и Unicode',
    'CIPHER_TOOL_TRUST_API' => 'Подходит для API и payload-данных',
    'CIPHER_TOOL_TRUST_PRIVATE' => 'Ввод не отправляется на сервер',
    // Cipher tool settings labels
    'CIPHER_TOOL_SETTING_ALPHABET'        => 'Алфавит',
    'CIPHER_TOOL_SETTING_AUTO'            => 'Авто',
    'CIPHER_TOOL_SETTING_KEY'             => 'Ключ',
    'CIPHER_TOOL_SETTING_KEY_PLACEHOLDER' => 'Введите ключ',
    'CIPHER_TOOL_SETTING_DELIMITER'       => 'Разделитель',
    'CIPHER_TOOL_SETTING_SPACE'           => 'Пробел',
    'CIPHER_TOOL_SETTING_SHIFT'           => 'Сдвиг',
    'CIPHER_TOOL_SETTING_KEY_EXAMPLE'     => 'Например: 314159',

    'LANG_EN' => 'Английский',
    'LANG_RU' => 'Русский',
    'LANG_ES' => 'Испанский',
    'LANG_PT' => 'Португальский',
    'LANG_TR' => 'Турецкий',
    'LANG_FR' => 'Французский',
    'LANG_DE' => 'Немецкий',
    'LANG_IT' => 'Итальянский',

    'PLAYFAIR_ERR_INVALID'              => 'Некорректные входные данные.',
    'PLAYFAIR_ERR_DIRECTION'            => 'Направление должно быть encrypt или decrypt.',
    'PLAYFAIR_ERR_TEXT_REQUIRED'        => 'Текст обязателен.',
    'PLAYFAIR_ERR_KEY_REQUIRED'         => 'Ключ обязателен.',
    'PLAYFAIR_ERR_ALPHABET_UNSUPPORTED' => 'Выбранный алфавит не поддерживается.',
    'PLAYFAIR_ERR_TEXT_ALPHABET'        => 'Текст не содержит символов выбранного алфавита.',
    'PLAYFAIR_ERR_KEY_ALPHABET'         => 'Ключ не содержит символов выбранного алфавита.',
    // Caesar errors
    'CAESAR_ERR_INVALID'              => 'Некорректные входные данные.',
    'CAESAR_ERR_DIRECTION'            => 'Направление должно быть encrypt или decrypt.',
    'CAESAR_ERR_TEXT_REQUIRED'        => 'Текст обязателен.',
    'CAESAR_ERR_ALPHABET_UNSUPPORTED' => 'Выбранный алфавит не поддерживается.',
    'CAESAR_ERR_TEXT_ALPHABET'        => 'Текст не содержит символов выбранного алфавита.',
    'CAESAR_ERR_SHIFT'                => 'Сдвиг должен быть в диапазоне 0-:max.',
    // Beaufort errors
    'BEAUFORT_ERR_INVALID'              => 'Некорректные входные данные.',
    'BEAUFORT_ERR_DIRECTION'            => 'Направление должно быть encrypt или decrypt.',
    'BEAUFORT_ERR_TEXT_REQUIRED'        => 'Текст обязателен.',
    'BEAUFORT_ERR_KEY_REQUIRED'         => 'Ключ обязателен.',
    'BEAUFORT_ERR_ALPHABET_UNSUPPORTED' => 'Выбранный алфавит не поддерживается.',
    'BEAUFORT_ERR_TEXT_ALPHABET'        => 'Текст не содержит символов выбранного алфавита.',
    'BEAUFORT_ERR_KEY_ALPHABET'         => 'Ключ не содержит символов выбранного алфавита.',
    // Gronsfeld errors
    'GRONSFELD_ERR_INVALID'              => 'Некорректные входные данные.',
    'GRONSFELD_ERR_DIRECTION'            => 'Направление должно быть encrypt или decrypt.',
    'GRONSFELD_ERR_TEXT_REQUIRED'        => 'Текст обязателен.',
    'GRONSFELD_ERR_KEY_INVALID'          => 'Ключ должен состоять только из цифр 0-9 и содержать от 1 до 32 символов.',
    'GRONSFELD_ERR_ALPHABET_UNSUPPORTED' => 'Выбранный алфавит не поддерживается.',
    'GRONSFELD_ERR_TEXT_ALPHABET'        => 'Текст не содержит символов выбранного алфавита.',
    'PLAYFAIR_DECODE_NOTE'              => 'Плейфер вставляет буквы-заполнители при шифровании. Удалите лишние символы (обычно А или Х) для восстановления исходного текста.',
    'PLAYFAIR_TRUST_CLIENT_SIDE'        => 'Классический биграммный шифр',
    'PLAYFAIR_TRUST_PRIVATE'            => 'Настраиваемое ключевое слово',
    'PLAYFAIR_TRUST_MULTILANG'          => 'Поддержка разных алфавитов',
    'PLAYFAIR_TRUST_KEY_BASED'          => 'Мы не сохраняем ваши сообщения',
    // Shared cipher trust keys
    'CIPHER_TOOL_TRUST_SERVER'         => 'Вычисления выполняются на сервере',
    'CIPHER_TOOL_TRUST_NO_STORAGE'     => 'Мы не сохраняем ваши сообщения',
    'CIPHER_TOOL_TRUST_MULTI_ALPHA'    => 'Поддержка разных алфавитов',
    'CIPHER_TOOL_TRUST_POLYALPHA'      => 'Многоалфавитный шифр подстановки',
    'CIPHER_TOOL_TRUST_CUSTOM_KEY'       => 'Настраиваемое ключевое слово',
    'CIPHER_TOOL_TRUST_CUSTOM_DELIMITER' => 'Настраиваемые разделители',
    // Caesar
    'CAESAR_TRUST_TYPE'                => 'Шифр простой замены со сдвигом',
    // Atbash
    'ATBASH_TRUST_RECIPROCAL'          => 'Самообратный: шифрование равно дешифрованию',
    'ATBASH_TRUST_KEYLESS'             => 'Ключ не требуется',
    // Beaufort
    'BEAUFORT_TRUST_RECIPROCAL'        => 'Один ключ для шифрования и дешифрования',
    // Gronsfeld
    'GRONSFELD_TRUST_NUMERIC'          => 'Ключ — последовательность цифр от 0 до 9',
    // Vernam
    'VERNAM_TRUST_OTP'                 => 'Схема одноразового блокнота',
    'VERNAM_TRUST_KEY_LENGTH'          => 'Ключ должен совпадать с длиной сообщения',
    'VERNAM_KEY_HINT'                  => 'Для максимальной безопасности используйте случайный ключ той же длины, что и сообщение, и никогда не используйте его повторно.',
    'VERNAM_GENERATE_KEY'              => 'Сгенерировать случайный ключ',
    'VERNAM_ERROR_DIRECTION'           => 'Направление должно быть encrypt или decrypt.',
    'VERNAM_ERROR_TEXT_REQUIRED'       => 'Текст обязателен.',
    'VERNAM_ERROR_KEY_REQUIRED'        => 'Ключ обязателен.',
    'VERNAM_WARNING_KEY_SHORT'         => 'Ключ короче сообщения и будет повторяться — это нарушает гарантию одноразового блокнота.',
    // Bacon
    'BACON_TRUST_STEGO'                => 'Скрывайте сообщения в обычном тексте',
    'BACON_TRUST_BINARY'               => 'Классическое кодирование Бэкона A/B',
    'BACON_TRUST_STEGANOGRAPHY'        => 'Поддержка режима стеганографии',
    'BACON_ERR_DIRECTION'              => 'Направление должно быть encrypt или decrypt.',
    'BACON_ERR_TEXT_REQUIRED'          => 'Текст обязателен.',
    'BACON_ERR_ALPHABET_UNSUPPORTED'   => 'Выбранный алфавит не поддерживается.',
    'BACON_ERR_TEXT_ALPHABET'          => 'Текст не содержит символов выбранного алфавита.',
    'BACON_ERR_COVER_TOO_SHORT'        => 'Текст-обёртка слишком короткий: нужно минимум :needed букв, найдено :available.',
    'BACON_COVER_LABEL'                => 'Текст-обёртка (необязательно)',
    'BACON_COVER_LABEL_SHORT'          => 'Текст-обёртка',
    'BACON_COVER_PLACEHOLDER'          => 'Введите текст, внутри которого будет скрыто сообщение…',
    'BACON_COVER_HINT'                 => 'Если заполнено, секрет кодируется регистром букв. Оставьте пустым для стандартного вывода A/B.',
    // A1Z26
    'A1Z26_TRUST_POSITIONAL'           => 'Каждая буква — её порядковый номер в алфавите',
    // Base64
    'BASE64_TRUST_PURPOSE'             => 'Кодирование бинарных данных в текст',
    'BASE64_TRUST_USES'                => 'Широко применяется в API, email и веб',
    // Hex
    'HEX_TRUST_PURPOSE'                => 'Шестнадцатеричное представление байтов',
    'HEX_TRUST_DEBUG'                  => 'Удобно для отладки и анализа данных',
    // URL encode
    'URL_TRUST_PURPOSE'                => 'Безопасная передача данных в URL',
    'URL_TRUST_STANDARD'               => 'Соответствует стандарту RFC 3986',
    // Binary converter
    'BINARY_TRUST_PURPOSE'             => 'Преобразование текста в двоичный код',
    'BINARY_TRUST_LEVEL'               => 'Побайтовое кодирование символов',
    // ASCII converter
    'ASCII_TRUST_PURPOSE'              => 'Преобразование текста в числовые коды ASCII',
    'ASCII_TRUST_TABLE'                => 'Поддержка расширенной таблицы символов',
    'ASCII_TRUST_USE'                  => 'Полезно при работе с низкоуровневыми данными',
    // Unicode converter
    'UNICODE_TRUST_PURPOSE'            => 'Преобразование в кодовые точки Unicode',
    'UNICODE_TRUST_EMOJI'              => 'Поддержка эмодзи и многоязычного текста',
    'UNICODE_TRUST_FORMATS'            => 'Форматы U+XXXX и \uXXXX',
    // JWT decoder
    'JWT_TRUST_PURPOSE'                => 'Декодирование токена без проверки подписи',
    'JWT_TRUST_PARTS'                  => 'Просмотр заголовка и полезной нагрузки',
    'JWT_TRUST_KEYLESS'                => 'Ключ не требуется для чтения содержимого',
];
